networks:

  secure_net: # Secure Network under VPN
    name: secure_network
    ipam:
      config:
        - subnet: 172.39.0.0/24 # Only last Octet

services:

  gluetun: # VPN Client
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun # If running on an LXC see readme for more info.
    networks:
      secure_net:
        ipv4_address: 172.39.0.2
    ports:
      - 8112:8112 # deluge web interface
      - 6881:6881 # deluge torrent port
      - 6881:6881/udp # deluge torrent port
      # - 6789:6789 # nzbget

      # Port forwarding required if attaching containers to gluetun network
      # - 9696:9696 # prowlarr
      # - 7878:7878 # radarr
      # - 8989:8989 # sonarr
      # - 8191:8191 # flaresolverr
    volumes:
      - ./gluetun:/gluetun
      - ./wg0.conf:/gluetun/wireguard/wg0.conf # bind-mount wireguard configuration file
    # Make a '.env' file in the same directory.
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - WEBUI_PORT=8112 # must match "deluge web interface" port number in gluetun's service above
      # - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS} # airvpn forwarded port, pulled from .env
    volumes:
      - ./deluge:/config
      - /media/4tb/Downloads:/downloads
      - /media/4tb/data/torrents:/data/torrents # Have to link as /data so *arr can read the path as they also use /data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    restart: unless-stopped

    ports:
      - 8191:8191 # flaresolverr
    
    networks:
        secure_net:
          ipv4_address: 172.39.0.5

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    restart: unless-stopped

    ports:
      - 9696:9696 # prowlarr

    networks:
        secure_net:
          ipv4_address: 172.39.0.6

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - /media/4tb/plexMovies:/media
      - /media/4tb/data:/data

    ports:
      - 8989:8989 # sonarr

    networks:
      secure_net:
        ipv4_address: 172.39.0.7

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - /media/4tb/plexMovies:/media
      - /media/4tb/data:/data

    ports:
      - 7878:7878 # radarr

    networks:
      secure_net:
        ipv4_address: 172.39.0.8